import type { RiskClass } from "./policy";

export type PendingActionStatus =
  | "pending"
  | "approved"
  | "denied"
  | "executed"
  | "failed";

export interface PendingAction {
  /** Unique identifier — matches the approvalId generated by ApprovalSurfaceAgent */
  approvalId: string;
  /** The action type, e.g. "email.send", "calendar.create" */
  actionType: string;
  /** Human-readable description of what the action will do */
  description: string;
  /** Risk class assigned by the policy engine */
  riskClass: RiskClass;
  /** Current lifecycle status */
  status: PendingActionStatus;
  /** The surface agent or source that proposed this action */
  sourceSurface: string;
  /** Opaque context needed to execute the action (e.g. connector id, params) */
  actionContext: unknown;
  /** Pipeline trace id for correlation */
  traceId: string;
  /** Epoch ms when the action was created */
  createdAt: number;
  /** Epoch ms when the status last changed */
  updatedAt: number;
  /** Optional reason for denial or failure */
  statusReason?: string;
}

/**
 * Interface for the pending action store.
 * Allows swapping in-memory for persistent backends later.
 */
export interface IPendingActionStore {
  /** Register a new pending action. Throws if approvalId already exists. */
  add(action: PendingAction): void;
  /** Retrieve an action by its approvalId. Returns undefined if not found. */
  get(approvalId: string): PendingAction | undefined;
  /** List actions, optionally filtered by status. Newest first. */
  list(status?: PendingActionStatus): PendingAction[];
  /** Transition an action to "approved". Throws if not currently "pending". */
  approve(approvalId: string): PendingAction;
  /** Transition an action to "denied" with an optional reason. */
  deny(approvalId: string, reason?: string): PendingAction;
  /** Mark an approved action as "executed". */
  markExecuted(approvalId: string): PendingAction;
  /** Mark an approved action as "failed" with a reason. */
  markFailed(approvalId: string, reason: string): PendingAction;
  /** Remove all actions older than the given age in milliseconds. */
  prune(maxAgeMs: number): number;
}
